#! /bin/bash

echo "UPDATING APT INDEX"
sudo apt update

if [[ -n $(which curl) ]]; then
    echo "Curl installed"
else
    read -p "Install Curl? (required to continue) [yq]" doCurl
    if [[ $doCurl = "y" ]]; then
        echo "INSTALLING CURL"
        sudo apt install curl
    elif [[ $doCurl = "q" ]]; then
        exit 0
    fi
fi

if [[ -n $(which git) ]]; then
    echo "Git installed"
else
    read -p "Install Git? (required to continue) [yq]" doGit
    if [[ $doGit = "y" ]]; then
        echo "INSTALLING GIT"
        sudo apt install git
    elif [[ $doGit = "q" ]]; then
        exit 0
    fi
fi

if [[ (-n $(which ruby)) || (-n $(which gem)) ]]; then
    echo "Ruby installed"
else
    read -p "Install Ruby? (required to continue) [yq]" doRuby
    if [[ $doRuby = "y" ]]; then
        echo "INSTALLING RUBY"
        sudo apt install ruby-full
    elif [[ $doRuby = "q" ]]; then
        exit 0
    fi
fi

if [[ -n $(which rake) ]]; then
    echo "Rake installed"
else
    read -p "Install Rake? (required to continue) [yq]" doRake
    if [[ $doRake = "y" ]]; then
        echo "INSTALLING RAKE"
        sudo apt install ruby-full
    elif [[ $doRake = "q" ]]; then
        exit 0f
    fi
fi

rake install
rake_status=$?

if [[ $rake_status = 0 ]]; then
    if ! [[ $PATH =~ (?:^|:)(\/usr\/local\/bin)(?:$|:) ]]; then
        echo "Adding /usr/local/bin to PATH"
        export PATH=/usr/local/bin:$PATH
    fi

    if [[ -n $(which python3) ]]; then
        echo "Python installed"
    else
        read -p "Install Python with pip? [ynq]" doPy
        if [[ $doPy = "y" ]]; then
            echo "INSTALLING PYTHON 3"
            sudo apt install python
        elif [[ $doPy = "q" ]]; then
            exit 0
        fi
    fi

    if [[ -n $(which n) ]]; then
        echo "n and node installed"
    else
        read -p "Install n and node? (installs build-essentials for make dependency if needed) [ynq]" doNode
        if [[ $doNode = "y" ]]; then
            if [[ -n $(which make) ]]; then
                echo "MAKE INSTALLED"
            else 
                echo "INSTALLING BUILD ESSENTIAL"
                sudo apt install build-essential
            fi
            echo "INSTALLING NODEJS AND NPM"
            git clone https://github.com/tj/n.git "$HOME/n"
            cd $HOME/n
            PREFIX=$HOME/.n make install
            cd ..
            sudo rm -rf $HOME/n  
            export N_PREFIX=$HOME/.n
            export PATH=$N_PREFIX/bin:$PATH
            . /etc/environment
            n latest
            n lts
        elif [[ $doNode = "q" ]]; then
            exit 0
        fi
    fi
else
    exit 0
fi



